FROM node:18-alpine

RUN npm install -g pnpm

# ARG BACKEND_URL
# ENV BACKEND_URL=${BACKEND_URL}

WORKDIR /app

COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./packages ./packages
COPY ./apps/web ./apps/web

RUN pnpm install --frozen-lockfile

RUN pnpm build

EXPOSE 3000

CMD ["pnpm", "run", "start:web"]