import "../globals.css";
import "@repo/ui/styles.css";
import type { Metadata } from "next";
import LogoPage from "@/components/Signupnav";
import { ToastProvider } from "@/components/Toastcontainer";


export const metadata: Metadata = {
  title: "Viraj multipurpose hall",
  description: "Generated by sj",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <LogoPage />
        {children}
      <ToastProvider aria-label="Notification" /> 
        </body>
    </html>
  );
}
